name: .NET Test

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
  release:
    name: Release 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build release
      run: dotnet publish -o release
    - name: Zip release files
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r Devops.zip release
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        files: Devops.zip
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./DevopsProject/Dockerfile
          platforms: linux/amd64
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/devops:latest
