name: .NET Test

on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build
  release:
    name: Release 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build release
      run: dotnet publish -o release
    - name: Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: release/
        name: ReleaseBuild
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./DevopsProject/Dockerfile
          target: build
          load: true
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./DevopsProject/Dockerfile
          platforms: linux/amd64
          push: true
          target: final
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/raduga:latest
